project 'OpenSSL_Crypto'
	configuration '*Static'
		kind 'StaticLib'
	configuration 'not *Static'
		kind 'SharedLib'
	configuration '*'
	language 'C++'
	uuid '617992C9-816A-4AFB-9F74-4FD2C02D8788'

	flags {
		'Unicode'
	}
	
	configuration 'Release*'
		flags {
			'Optimize'
		}
	configuration '*'
	
	targetdir '../Build/%{cfg.platform}/%{cfg.shortname}'
	objdir '../BuildIntermediate/%{cfg.platform}/%{cfg.shortname}'
	
	files {
		-- public headers
		'*.h',
		'inc32/*.h',
		-- private headers
		'crypto/md5/*.h',
		'crypto/sha/*.h',
		'crypto/ripemd/*.h',
		'crypto/des/*.h',
		'crypto/rc2/*.h',
		'crypto/rc4/*.h',
		'crypto/bf/*.h',
		'crypto/idea/*.h',
		'crypto/cast/*.h',
		'crypto/ripemd/*.h',
		'crypto/aes/*.h',
		'crypto/camellia/*.h',
		'crypto/seed/*.h',
		'crypto/modes/*.h',
		'crypto/bn/*.h',
		'crypto/dsa/*.h',
		'crypto/ec/*.h',
		'crypto/ecdh/*.h',
		'crypto/ecdsa/*.h',
		'crypto/bio/*.h',
		'crypto/objects/*.h',
		'crypto/evp/*.h',
		'crypto/asn1/*.h',
		'crypto/x509v3/*.h',
		'crypto/cms/*.h',
		'crypto/conf/*.h',
		'crypto/ui/*.h',
		'crypto/whrlpool/*.h',
		-- sources
		'crypto/cryptlib.c',
		'crypto/mem.c',
		'crypto/mem_dbg.c',
		'crypto/cversion.c',
		'crypto/ex_data.c',
		'crypto/cpt_err.c',
		'crypto/ebcdic.c',
		'crypto/uid.c',
		'crypto/o_time.c',
		'crypto/o_str.c',
		'crypto/o_dir.c',
		'crypto/o_fips.c',
		'crypto/o_init.c',
		'crypto/fips_ers.c',
		'crypto/mem_clr.c',
		'crypto/md4/md4_dgst.c',
		'crypto/md4/md4_one.c',
		'crypto/md5/md5_dgst.c',
		'crypto/md5/md5_one.c',
		'crypto/sha/sha_dgst.c',
		'crypto/sha/sha1dgst.c',
		'crypto/sha/sha_one.c',
		'crypto/sha/sha1_one.c',
		'crypto/sha/sha256.c',
		'crypto/sha/sha512.c',
		'crypto/mdc2/mdc2dgst.c',
		'crypto/mdc2/mdc2_one.c',
		'crypto/hmac/hmac.c',
		'crypto/hmac/hm_ameth.c',
		'crypto/hmac/hm_pmeth.c',
		'crypto/cmac/cmac.c',
		'crypto/cmac/cm_ameth.c',
		'crypto/cmac/cm_pmeth.c',
		'crypto/ripemd/rmd_dgst.c',
		'crypto/ripemd/rmd_one.c',
		'crypto/des/set_key.c',
		'crypto/des/ecb_enc.c',
		'crypto/des/cbc_enc.c',
		'crypto/des/ecb3_enc.c',
		'crypto/des/cfb64enc.c',
		'crypto/des/cfb64ede.c',
		'crypto/des/cfb_enc.c',
		'crypto/des/ofb64ede.c',
		'crypto/des/enc_read.c',
		'crypto/des/enc_writ.c',
		'crypto/des/ofb64enc.c',
		'crypto/des/ofb_enc.c',
		'crypto/des/str2key.c',
		'crypto/des/pcbc_enc.c',
		'crypto/des/qud_cksm.c',
		'crypto/des/rand_key.c',
		'crypto/des/des_enc.c',
		'crypto/des/fcrypt_b.c',
		'crypto/des/fcrypt.c',
		'crypto/des/xcbc_enc.c',
		'crypto/des/rpc_enc.c',
		'crypto/des/cbc_cksm.c',
		'crypto/des/ede_cbcm_enc.c',
		'crypto/des/des_old.c',
		'crypto/des/des_old2.c',
		'crypto/des/read2pwd.c',
		'crypto/rc2/rc2_ecb.c',
		'crypto/rc2/rc2_skey.c',
		'crypto/rc2/rc2_cbc.c',
		'crypto/rc2/rc2cfb64.c',
		'crypto/rc2/rc2ofb64.c',
		'crypto/rc4/rc4_enc.c',
		'crypto/rc4/rc4_skey.c',
		'crypto/rc4/rc4_utl.c',
		'crypto/idea/i_cbc.c',
		'crypto/idea/i_cfb64.c',
		'crypto/idea/i_ofb64.c',
		'crypto/idea/i_ecb.c',
		'crypto/idea/i_skey.c',
		'crypto/bf/bf_skey.c',
		'crypto/bf/bf_ecb.c',
		'crypto/bf/bf_enc.c',
		'crypto/bf/bf_cfb64.c',
		'crypto/bf/bf_ofb64.c',
		'crypto/cast/c_skey.c',
		'crypto/cast/c_ecb.c',
		'crypto/cast/c_enc.c',
		'crypto/cast/c_cfb64.c',
		'crypto/cast/c_ofb64.c',
		'crypto/aes/aes_misc.c',
		'crypto/aes/aes_ecb.c',
		'crypto/aes/aes_cfb.c',
		'crypto/aes/aes_ofb.c',
		'crypto/aes/aes_ctr.c',
		'crypto/aes/aes_ige.c',
		'crypto/aes/aes_wrap.c',
		'crypto/aes/aes_core.c',
		'crypto/aes/aes_cbc.c',
		'crypto/camellia/cmll_ecb.c',
		'crypto/camellia/cmll_ofb.c',
		'crypto/camellia/cmll_cfb.c',
		'crypto/camellia/cmll_ctr.c',
		'crypto/camellia/cmll_utl.c',
		'crypto/camellia/camellia.c',
		'crypto/camellia/cmll_misc.c',
		'crypto/camellia/cmll_cbc.c',
		'crypto/seed/seed.c',
		'crypto/seed/seed_ecb.c',
		'crypto/seed/seed_cbc.c',
		'crypto/seed/seed_cfb.c',
		'crypto/seed/seed_ofb.c',
		'crypto/modes/cbc128.c',
		'crypto/modes/ctr128.c',
		'crypto/modes/cts128.c',
		'crypto/modes/cfb128.c',
		'crypto/modes/ofb128.c',
		'crypto/modes/gcm128.c',
		'crypto/modes/ccm128.c',
		'crypto/modes/xts128.c',
		'crypto/bn/bn_add.c',
		'crypto/bn/bn_div.c',
		'crypto/bn/bn_exp.c',
		'crypto/bn/bn_lib.c',
		'crypto/bn/bn_ctx.c',
		'crypto/bn/bn_mul.c',
		'crypto/bn/bn_mod.c',
		'crypto/bn/bn_print.c',
		'crypto/bn/bn_rand.c',
		'crypto/bn/bn_shift.c',
		'crypto/bn/bn_word.c',
		'crypto/bn/bn_blind.c',
		'crypto/bn/bn_kron.c',
		'crypto/bn/bn_sqrt.c',
		'crypto/bn/bn_gcd.c',
		'crypto/bn/bn_prime.c',
		'crypto/bn/bn_err.c',
		'crypto/bn/bn_sqr.c',
		'crypto/bn/bn_asm.c',
		'crypto/bn/bn_recp.c',
		'crypto/bn/bn_mont.c',
		'crypto/bn/bn_mpi.c',
		'crypto/bn/bn_exp2.c',
		'crypto/bn/bn_gf2m.c',
		'crypto/bn/bn_nist.c',
		'crypto/bn/bn_depr.c',
		'crypto/bn/bn_const.c',
		'crypto/bn/bn_x931p.c',
		'crypto/rsa/rsa_eay.c',
		'crypto/rsa/rsa_gen.c',
		'crypto/rsa/rsa_lib.c',
		'crypto/rsa/rsa_sign.c',
		'crypto/rsa/rsa_saos.c',
		'crypto/rsa/rsa_err.c',
		'crypto/rsa/rsa_pk1.c',
		'crypto/rsa/rsa_ssl.c',
		'crypto/rsa/rsa_none.c',
		'crypto/rsa/rsa_oaep.c',
		'crypto/rsa/rsa_chk.c',
		'crypto/rsa/rsa_null.c',
		'crypto/rsa/rsa_pss.c',
		'crypto/rsa/rsa_x931.c',
		'crypto/rsa/rsa_asn1.c',
		'crypto/rsa/rsa_depr.c',
		'crypto/rsa/rsa_ameth.c',
		'crypto/rsa/rsa_prn.c',
		'crypto/rsa/rsa_pmeth.c',
		'crypto/rsa/rsa_crpt.c',
		'crypto/dsa/dsa_gen.c',
		'crypto/dsa/dsa_key.c',
		'crypto/dsa/dsa_lib.c',
		'crypto/dsa/dsa_asn1.c',
		'crypto/dsa/dsa_vrf.c',
		'crypto/dsa/dsa_sign.c',
		'crypto/dsa/dsa_err.c',
		'crypto/dsa/dsa_ossl.c',
		'crypto/dsa/dsa_depr.c',
		'crypto/dsa/dsa_ameth.c',
		'crypto/dsa/dsa_pmeth.c',
		'crypto/dsa/dsa_prn.c',
		'crypto/dso/dso_dl.c',
		'crypto/dso/dso_dlfcn.c',
		'crypto/dso/dso_err.c',
		'crypto/dso/dso_lib.c',
		'crypto/dso/dso_null.c',
		'crypto/dso/dso_openssl.c',
		'crypto/dso/dso_win32.c',
		'crypto/dso/dso_vms.c',
		'crypto/dso/dso_beos.c',
		'crypto/dh/dh_asn1.c',
		'crypto/dh/dh_gen.c',
		'crypto/dh/dh_key.c',
		'crypto/dh/dh_lib.c',
		'crypto/dh/dh_check.c',
		'crypto/dh/dh_err.c',
		'crypto/dh/dh_depr.c',
		'crypto/dh/dh_ameth.c',
		'crypto/dh/dh_pmeth.c',
		'crypto/dh/dh_prn.c',
		'crypto/ec/ec_lib.c',
		'crypto/ec/ecp_smpl.c',
		'crypto/ec/ecp_mont.c',
		'crypto/ec/ecp_nist.c',
		'crypto/ec/ec_cvt.c',
		'crypto/ec/ec_mult.c',
		'crypto/ec/ec_err.c',
		'crypto/ec/ec_curve.c',
		'crypto/ec/ec_check.c',
		'crypto/ec/ec_print.c',
		'crypto/ec/ec_asn1.c',
		'crypto/ec/ec_key.c',
		'crypto/ec/ec2_smpl.c',
		'crypto/ec/ec2_mult.c',
		'crypto/ec/ec_ameth.c',
		'crypto/ec/ec_pmeth.c',
		'crypto/ec/eck_prn.c',
		'crypto/ec/ecp_nistp224.c',
		'crypto/ec/ecp_nistp256.c',
		'crypto/ec/ecp_nistp521.c',
		'crypto/ec/ecp_nistputil.c',
		'crypto/ec/ecp_oct.c',
		'crypto/ec/ec2_oct.c',
		'crypto/ec/ec_oct.c',
		'crypto/ecdh/ech_lib.c',
		'crypto/ecdh/ech_ossl.c',
		'crypto/ecdh/ech_key.c',
		'crypto/ecdh/ech_err.c',
		'crypto/ecdsa/ecs_lib.c',
		'crypto/ecdsa/ecs_asn1.c',
		'crypto/ecdsa/ecs_ossl.c',
		'crypto/ecdsa/ecs_sign.c',
		'crypto/ecdsa/ecs_vrf.c',
		'crypto/ecdsa/ecs_err.c',
		'crypto/buffer/buffer.c',
		'crypto/buffer/buf_str.c',
		'crypto/buffer/buf_err.c',
		'crypto/bio/bio_lib.c',
		'crypto/bio/bio_cb.c',
		'crypto/bio/bio_err.c',
		'crypto/bio/bss_mem.c',
		'crypto/bio/bss_null.c',
		'crypto/bio/bss_fd.c',
		'crypto/bio/bss_file.c',
		'crypto/bio/bss_sock.c',
		'crypto/bio/bss_conn.c',
		'crypto/bio/bf_null.c',
		'crypto/bio/bf_buff.c',
		'crypto/bio/b_print.c',
		'crypto/bio/b_dump.c',
		'crypto/bio/b_sock.c',
		'crypto/bio/bss_acpt.c',
		'crypto/bio/bf_nbio.c',
		'crypto/bio/bss_log.c',
		'crypto/bio/bss_bio.c',
		'crypto/bio/bss_dgram.c',
		'crypto/stack/stack.c',
		'crypto/lhash/lhash.c',
		'crypto/lhash/lh_stats.c',
		'crypto/rand/md_rand.c',
		'crypto/rand/randfile.c',
		'crypto/rand/rand_lib.c',
		'crypto/rand/rand_err.c',
		'crypto/rand/rand_egd.c',
		'crypto/rand/rand_win.c',
		'crypto/rand/rand_unix.c',
		'crypto/rand/rand_os2.c',
		'crypto/rand/rand_nw.c',
		'crypto/err/err.c',
		'crypto/err/err_all.c',
		'crypto/err/err_prn.c',
		'crypto/objects/o_names.c',
		'crypto/objects/obj_dat.c',
		'crypto/objects/obj_lib.c',
		'crypto/objects/obj_err.c',
		'crypto/objects/obj_xref.c',
		'crypto/evp/encode.c',
		'crypto/evp/digest.c',
		'crypto/evp/evp_enc.c',
		'crypto/evp/evp_key.c',
		'crypto/evp/evp_acnf.c',
		'crypto/evp/evp_cnf.c',
		'crypto/evp/e_des.c',
		'crypto/evp/e_bf.c',
		'crypto/evp/e_idea.c',
		'crypto/evp/e_des3.c',
		'crypto/evp/e_camellia.c',
		'crypto/evp/e_rc4.c',
		'crypto/evp/e_aes.c',
		'crypto/evp/names.c',
		'crypto/evp/e_seed.c',
		'crypto/evp/e_xcbc_d.c',
		'crypto/evp/e_rc2.c',
		'crypto/evp/e_cast.c',
		'crypto/evp/e_rc5.c',
		'crypto/evp/m_null.c',
		'crypto/evp/m_md4.c',
		'crypto/evp/m_md5.c',
		'crypto/evp/m_sha.c',
		'crypto/evp/m_sha1.c',
		'crypto/evp/m_wp.c',
		'crypto/evp/m_dss.c',
		'crypto/evp/m_dss1.c',
		'crypto/evp/m_mdc2.c',
		'crypto/evp/m_ripemd.c',
		'crypto/evp/m_ecdsa.c',
		'crypto/evp/p_open.c',
		'crypto/evp/p_seal.c',
		'crypto/evp/p_sign.c',
		'crypto/evp/p_verify.c',
		'crypto/evp/p_lib.c',
		'crypto/evp/p_enc.c',
		'crypto/evp/p_dec.c',
		'crypto/evp/bio_md.c',
		'crypto/evp/bio_b64.c',
		'crypto/evp/bio_enc.c',
		'crypto/evp/evp_err.c',
		'crypto/evp/e_null.c',
		'crypto/evp/c_all.c',
		'crypto/evp/c_allc.c',
		'crypto/evp/c_alld.c',
		'crypto/evp/evp_lib.c',
		'crypto/evp/bio_ok.c',
		'crypto/evp/evp_pkey.c',
		'crypto/evp/evp_pbe.c',
		'crypto/evp/p5_crpt.c',
		'crypto/evp/p5_crpt2.c',
		'crypto/evp/e_old.c',
		'crypto/evp/pmeth_lib.c',
		'crypto/evp/pmeth_fn.c',
		'crypto/evp/pmeth_gn.c',
		'crypto/evp/m_sigver.c',
		'crypto/evp/evp_fips.c',
		'crypto/evp/e_aes_cbc_hmac_sha1.c',
		'crypto/evp/e_rc4_hmac_md5.c',
		'crypto/asn1/a_object.c',
		'crypto/asn1/a_bitstr.c',
		'crypto/asn1/a_utctm.c',
		'crypto/asn1/a_gentm.c',
		'crypto/asn1/a_time.c',
		'crypto/asn1/a_int.c',
		'crypto/asn1/a_octet.c',
		'crypto/asn1/a_print.c',
		'crypto/asn1/a_type.c',
		'crypto/asn1/a_set.c',
		'crypto/asn1/a_dup.c',
		'crypto/asn1/a_d2i_fp.c',
		'crypto/asn1/a_i2d_fp.c',
		'crypto/asn1/a_enum.c',
		'crypto/asn1/a_utf8.c',
		'crypto/asn1/a_sign.c',
		'crypto/asn1/a_digest.c',
		'crypto/asn1/a_verify.c',
		'crypto/asn1/a_mbstr.c',
		'crypto/asn1/a_strex.c',
		'crypto/asn1/x_algor.c',
		'crypto/asn1/x_val.c',
		'crypto/asn1/x_pubkey.c',
		'crypto/asn1/x_sig.c',
		'crypto/asn1/x_req.c',
		'crypto/asn1/x_attrib.c',
		'crypto/asn1/x_bignum.c',
		'crypto/asn1/x_long.c',
		'crypto/asn1/x_name.c',
		'crypto/asn1/x_x509.c',
		'crypto/asn1/x_x509a.c',
		'crypto/asn1/x_crl.c',
		'crypto/asn1/x_info.c',
		'crypto/asn1/x_spki.c',
		'crypto/asn1/nsseq.c',
		'crypto/asn1/x_nx509.c',
		'crypto/asn1/d2i_pu.c',
		'crypto/asn1/d2i_pr.c',
		'crypto/asn1/i2d_pu.c',
		'crypto/asn1/i2d_pr.c',
		'crypto/asn1/t_req.c',
		'crypto/asn1/t_x509.c',
		'crypto/asn1/t_x509a.c',
		'crypto/asn1/t_crl.c',
		'crypto/asn1/t_pkey.c',
		'crypto/asn1/t_spki.c',
		'crypto/asn1/t_bitst.c',
		'crypto/asn1/tasn_new.c',
		'crypto/asn1/tasn_fre.c',
		'crypto/asn1/tasn_enc.c',
		'crypto/asn1/tasn_dec.c',
		'crypto/asn1/tasn_utl.c',
		'crypto/asn1/tasn_typ.c',
		'crypto/asn1/tasn_prn.c',
		'crypto/asn1/ameth_lib.c',
		'crypto/asn1/f_int.c',
		'crypto/asn1/f_string.c',
		'crypto/asn1/n_pkey.c',
		'crypto/asn1/f_enum.c',
		'crypto/asn1/x_pkey.c',
		'crypto/asn1/a_bool.c',
		'crypto/asn1/x_exten.c',
		'crypto/asn1/bio_asn1.c',
		'crypto/asn1/bio_ndef.c',
		'crypto/asn1/asn_mime.c',
		'crypto/asn1/asn1_gen.c',
		'crypto/asn1/asn1_par.c',
		'crypto/asn1/asn1_lib.c',
		'crypto/asn1/asn1_err.c',
		'crypto/asn1/a_bytes.c',
		'crypto/asn1/a_strnid.c',
		'crypto/asn1/evp_asn1.c',
		'crypto/asn1/asn_pack.c',
		'crypto/asn1/p5_pbe.c',
		'crypto/asn1/p5_pbev2.c',
		'crypto/asn1/p8_pkey.c',
		'crypto/asn1/asn_moid.c',
		'crypto/pem/pem_sign.c',
		'crypto/pem/pem_seal.c',
		'crypto/pem/pem_info.c',
		'crypto/pem/pem_lib.c',
		'crypto/pem/pem_all.c',
		'crypto/pem/pem_err.c',
		'crypto/pem/pem_x509.c',
		'crypto/pem/pem_xaux.c',
		'crypto/pem/pem_oth.c',
		'crypto/pem/pem_pk8.c',
		'crypto/pem/pem_pkey.c',
		'crypto/pem/pvkfmt.c',
		'crypto/x509/x509_def.c',
		'crypto/x509/x509_d2.c',
		'crypto/x509/x509_r2x.c',
		'crypto/x509/x509_cmp.c',
		'crypto/x509/x509_obj.c',
		'crypto/x509/x509_req.c',
		'crypto/x509/x509spki.c',
		'crypto/x509/x509_vfy.c',
		'crypto/x509/x509_set.c',
		'crypto/x509/x509cset.c',
		'crypto/x509/x509rset.c',
		'crypto/x509/x509_err.c',
		'crypto/x509/x509name.c',
		'crypto/x509/x509_v3.c',
		'crypto/x509/x509_ext.c',
		'crypto/x509/x509_att.c',
		'crypto/x509/x509type.c',
		'crypto/x509/x509_lu.c',
		'crypto/x509/x_all.c',
		'crypto/x509/x509_txt.c',
		'crypto/x509/x509_trs.c',
		'crypto/x509/by_file.c',
		'crypto/x509/by_dir.c',
		'crypto/x509/x509_vpm.c',
		'crypto/x509v3/v3_bcons.c',
		'crypto/x509v3/v3_bitst.c',
		'crypto/x509v3/v3_conf.c',
		'crypto/x509v3/v3_extku.c',
		'crypto/x509v3/v3_ia5.c',
		'crypto/x509v3/v3_lib.c',
		'crypto/x509v3/v3_prn.c',
		'crypto/x509v3/v3_utl.c',
		'crypto/x509v3/v3err.c',
		'crypto/x509v3/v3_genn.c',
		'crypto/x509v3/v3_alt.c',
		'crypto/x509v3/v3_skey.c',
		'crypto/x509v3/v3_akey.c',
		'crypto/x509v3/v3_pku.c',
		'crypto/x509v3/v3_int.c',
		'crypto/x509v3/v3_enum.c',
		'crypto/x509v3/v3_sxnet.c',
		'crypto/x509v3/v3_cpols.c',
		'crypto/x509v3/v3_crld.c',
		'crypto/x509v3/v3_purp.c',
		'crypto/x509v3/v3_info.c',
		'crypto/x509v3/v3_ocsp.c',
		'crypto/x509v3/v3_akeya.c',
		'crypto/x509v3/v3_pmaps.c',
		'crypto/x509v3/v3_pcons.c',
		'crypto/x509v3/v3_ncons.c',
		'crypto/x509v3/v3_pcia.c',
		'crypto/x509v3/v3_pci.c',
		'crypto/x509v3/pcy_cache.c',
		'crypto/x509v3/pcy_node.c',
		'crypto/x509v3/pcy_data.c',
		'crypto/x509v3/pcy_map.c',
		'crypto/x509v3/pcy_tree.c',
		'crypto/x509v3/pcy_lib.c',
		'crypto/x509v3/v3_asid.c',
		'crypto/x509v3/v3_addr.c',
		'crypto/cms/cms_lib.c',
		'crypto/cms/cms_asn1.c',
		'crypto/cms/cms_att.c',
		'crypto/cms/cms_io.c',
		'crypto/cms/cms_smime.c',
		'crypto/cms/cms_err.c',
		'crypto/cms/cms_sd.c',
		'crypto/cms/cms_dd.c',
		'crypto/cms/cms_cd.c',
		'crypto/cms/cms_env.c',
		'crypto/cms/cms_enc.c',
		'crypto/cms/cms_ess.c',
		'crypto/cms/cms_pwri.c',
		'crypto/conf/conf_err.c',
		'crypto/conf/conf_lib.c',
		'crypto/conf/conf_api.c',
		'crypto/conf/conf_def.c',
		'crypto/conf/conf_mod.c',
		'crypto/conf/conf_mall.c',
		'crypto/conf/conf_sap.c',
		'crypto/txt_db/txt_db.c',
		'crypto/pkcs7/pk7_asn1.c',
		'crypto/pkcs7/pk7_lib.c',
		'crypto/pkcs7/pkcs7err.c',
		'crypto/pkcs7/pk7_doit.c',
		'crypto/pkcs7/pk7_smime.c',
		'crypto/pkcs7/pk7_attr.c',
		'crypto/pkcs7/pk7_mime.c',
		'crypto/pkcs7/bio_pk7.c',
		'crypto/pkcs12/p12_add.c',
		'crypto/pkcs12/p12_asn.c',
		'crypto/pkcs12/p12_attr.c',
		'crypto/pkcs12/p12_crpt.c',
		'crypto/pkcs12/p12_crt.c',
		'crypto/pkcs12/p12_decr.c',
		'crypto/pkcs12/p12_init.c',
		'crypto/pkcs12/p12_key.c',
		'crypto/pkcs12/p12_kiss.c',
		'crypto/pkcs12/p12_mutl.c',
		'crypto/pkcs12/p12_utl.c',
		'crypto/pkcs12/p12_npas.c',
		'crypto/pkcs12/pk12err.c',
		'crypto/pkcs12/p12_p8d.c',
		'crypto/pkcs12/p12_p8e.c',
		'crypto/comp/comp_lib.c',
		'crypto/comp/comp_err.c',
		'crypto/comp/c_rle.c',
		'crypto/comp/c_zlib.c',
		'crypto/engine/eng_err.c',
		'crypto/engine/eng_lib.c',
		'crypto/engine/eng_list.c',
		'crypto/engine/eng_init.c',
		'crypto/engine/eng_ctrl.c',
		'crypto/engine/eng_table.c',
		'crypto/engine/eng_pkey.c',
		'crypto/engine/eng_fat.c',
		'crypto/engine/eng_all.c',
		'crypto/engine/tb_rsa.c',
		'crypto/engine/tb_dsa.c',
		'crypto/engine/tb_ecdsa.c',
		'crypto/engine/tb_dh.c',
		'crypto/engine/tb_ecdh.c',
		'crypto/engine/tb_rand.c',
		'crypto/engine/tb_store.c',
		'crypto/engine/tb_cipher.c',
		'crypto/engine/tb_digest.c',
		'crypto/engine/tb_pkmeth.c',
		'crypto/engine/tb_asnmth.c',
		'crypto/engine/eng_openssl.c',
		'crypto/engine/eng_cnf.c',
		'crypto/engine/eng_dyn.c',
		'crypto/engine/eng_cryptodev.c',
		'crypto/engine/eng_rsax.c',
		'crypto/engine/eng_rdrand.c',
		'crypto/ocsp/ocsp_asn.c',
		'crypto/ocsp/ocsp_ext.c',
		'crypto/ocsp/ocsp_ht.c',
		'crypto/ocsp/ocsp_lib.c',
		'crypto/ocsp/ocsp_cl.c',
		'crypto/ocsp/ocsp_srv.c',
		'crypto/ocsp/ocsp_prn.c',
		'crypto/ocsp/ocsp_vfy.c',
		'crypto/ocsp/ocsp_err.c',
		'crypto/ui/ui_err.c',
		'crypto/ui/ui_lib.c',
		'crypto/ui/ui_openssl.c',
		'crypto/ui/ui_util.c',
		'crypto/ui/ui_compat.c',
		'crypto/krb5/krb5_asn.c',
		'crypto/pqueue/pqueue.c',
		'crypto/whrlpool/wp_dgst.c',
		'crypto/whrlpool/wp_block.c',
		'crypto/ts/ts_err.c',
		'crypto/ts/ts_req_utils.c',
		'crypto/ts/ts_req_print.c',
		'crypto/ts/ts_rsp_utils.c',
		'crypto/ts/ts_rsp_print.c',
		'crypto/ts/ts_rsp_sign.c',
		'crypto/ts/ts_rsp_verify.c',
		'crypto/ts/ts_verify_ctx.c',
		'crypto/ts/ts_lib.c',
		'crypto/ts/ts_conf.c',
		'crypto/ts/ts_asn1.c',
		'crypto/srp/srp_lib.c',
		'crypto/srp/srp_vfy.c',
	}
	
	configuration 'Debug*'
		defines {
			'_DEBUG',
		}
		flags {
			"Symbols"
		}
	configuration 'not Debug*'
		defines {
			'NDEBUG'
		}
	configuration '*'
	
	defines {
		'OPENSSL_THREADS',
		'LIBSSH2_HAVE_ZLIB',
		'L_ENDIAN',
		'OPENSSL_NO_RC5',
		'OPENSSL_NO_MD2',
		'OPENSSL_NO_KRB5',
		'OPENSSL_NO_JPAKE',
	}
	
	configuration '*Static'
		files {
			'engines/e_4758cca.c',
			'engines/e_aep.c',
			'engines/e_atalla.c',
			'engines/e_cswift.c',
			'engines/e_gmp.c',
			'engines/e_chil.c',
			'engines/e_nuron.c',
			'engines/e_sureware.c',
			'engines/e_ubsec.c',
			'engines/e_padlock.c',
			'engines/e_capi.c',
			'engines/ccgost/e_gost_err.c',
			'engines/ccgost/gost2001_keyx.c',
			'engines/ccgost/gost2001.c',
			'engines/ccgost/gost89.c',
			'engines/ccgost/gost94_keyx.c',
			'engines/ccgost/gost_ameth.c',
			'engines/ccgost/gost_asn1.c',
			'engines/ccgost/gost_crypt.c',
			'engines/ccgost/gost_ctl.c',
			'engines/ccgost/gost_eng.c',
			'engines/ccgost/gosthash.c',
			'engines/ccgost/gost_keywrap.c',
			'engines/ccgost/gost_md.c',
			'engines/ccgost/gost_params.c',
			'engines/ccgost/gost_pmeth.c',
			'engines/ccgost/gost_sign.c'
		}	
		defines { 'OPENSSL_NO_DYNAMIC_ENGINE' }
	configuration 'not *Static'
		if os.is('windows') then
			files {
				'ms/applink.c',
				'ms/uplink.c',
			}
		end
	
		defines { 'OPENSSL_NO_STATIC_ENGINE' }
	configuration { 'not *Static', 'x32' }
		-- Use AppLink only in the x86 build since it requires NASM for x64
		defines { 'OPENSSL_USE_APPLINK' }
	configuration '*'
	
	includedirs {
		'.',
		'inc32',
		'crypto',
		'crypto/md5',
		'crypto/sha',
		'crypto/ripemd',
		'crypto/des',
		'crypto/rc2',
		'crypto/rc4',
		'crypto/bf',
		'crypto/idea',
		'crypto/cast',
		'crypto/ripemd',
		'crypto/aes',
		'crypto/camellia',
		'crypto/seed',
		'crypto/modes',
		'crypto/bn',
		'crypto/dsa',
		'crypto/ec',
		'crypto/ecdh',
		'crypto/ecdsa',
		'crypto/bio',
		'crypto/objects',
		'crypto/evp',
		'crypto/asn1',
		'crypto/x509v3',
		'crypto/cms',
		'crypto/conf',
		'crypto/ui',
		'crypto/whrlpool',
	}
	
	links {
		--
	}
	
	if os.is('windows') then
		defines {
			'NO_WINDOWS_BRAINDEATH',
			--'MK1MF_BUILD',
			'WIN32_LEAN_AND_MEAN',
			'DSO_WIN32',
			'OPENSSL_SYSNAME_WIN32',
			'_CRT_SECURE_NO_DEPRECATE'
		}
		
		links {
			'ws2_32',
			'crypt32'
		}
		
		prebuildcommands {
			'copy "..\\CoherentThirdPartyFiles\\libeay32.def" "ms\\LIBEAY32.def" /Y',
			'md "inc32\\openssl"',
			'copy "e_os2.h" "inc32\\openssl\\e_os2.h" /Y',
			'copy "crypto\\crypto.h" "inc32\\openssl\\crypto.h" /Y',
			'copy "crypto\\opensslv.h" "inc32\\openssl\\opensslv.h" /Y',
			--'copy "crypto\\opensslconf.h" "inc32\\openssl\\opensslconf.h" /Y',
			'copy "crypto\\ebcdic.h" "inc32\\openssl\\ebcdic.h" /Y',
			'copy "crypto\\symhacks.h" "inc32\\openssl\\symhacks.h" /Y',
			'copy "crypto\\ossl_typ.h" "inc32\\openssl\\ossl_typ.h" /Y',
			'copy "crypto\\md4\\md4.h" "inc32\\openssl\\md4.h" /Y',
			'copy "crypto\\md5\\md5.h" "inc32\\openssl\\md5.h" /Y',
			'copy "crypto\\sha\\sha.h" "inc32\\openssl\\sha.h" /Y',
			'copy "crypto\\mdc2\\mdc2.h" "inc32\\openssl\\mdc2.h" /Y',
			'copy "crypto\\hmac\\hmac.h" "inc32\\openssl\\hmac.h" /Y',
			'copy "crypto\\cmac\\cmac.h" "inc32\\openssl\\cmac.h" /Y',
			'copy "crypto\\ripemd\\ripemd.h" "inc32\\openssl\\ripemd.h" /Y',
			'copy "crypto\\des\\des.h" "inc32\\openssl\\des.h" /Y',
			'copy "crypto\\des\\des_old.h" "inc32\\openssl\\des_old.h" /Y',
			'copy "crypto\\rc2\\rc2.h" "inc32\\openssl\\rc2.h" /Y',
			'copy "crypto\\rc4\\rc4.h" "inc32\\openssl\\rc4.h" /Y',
			'copy "crypto\\idea\\idea.h" "inc32\\openssl\\idea.h" /Y',
			'copy "crypto\\bf\\blowfish.h" "inc32\\openssl\\blowfish.h" /Y',
			'copy "crypto\\cast\\cast.h" "inc32\\openssl\\cast.h" /Y',
			'copy "crypto\\aes\\aes.h" "inc32\\openssl\\aes.h" /Y',
			'copy "crypto\\camellia\\camellia.h" "inc32\\openssl\\camellia.h" /Y',
			'copy "crypto\\seed\\seed.h" "inc32\\openssl\\seed.h" /Y',
			'copy "crypto\\modes\\modes.h" "inc32\\openssl\\modes.h" /Y',
			'copy "crypto\\bn\\bn.h" "inc32\\openssl\\bn.h" /Y',
			'copy "crypto\\rsa\\rsa.h" "inc32\\openssl\\rsa.h" /Y',
			'copy "crypto\\dsa\\dsa.h" "inc32\\openssl\\dsa.h" /Y',
			'copy "crypto\\dso\\dso.h" "inc32\\openssl\\dso.h" /Y',
			'copy "crypto\\dh\\dh.h" "inc32\\openssl\\dh.h" /Y',
			'copy "crypto\\ec\\ec.h" "inc32\\openssl\\ec.h" /Y',
			'copy "crypto\\ecdh\\ecdh.h" "inc32\\openssl\\ecdh.h" /Y',
			'copy "crypto\\ecdsa\\ecdsa.h" "inc32\\openssl\\ecdsa.h" /Y',
			'copy "crypto\\buffer\\buffer.h" "inc32\\openssl\\buffer.h" /Y',
			'copy "crypto\\bio\\bio.h" "inc32\\openssl\\bio.h" /Y',
			'copy "crypto\\stack\\stack.h" "inc32\\openssl\\stack.h" /Y',
			'copy "crypto\\stack\\safestack.h" "inc32\\openssl\\safestack.h" /Y',
			'copy "crypto\\lhash\\lhash.h" "inc32\\openssl\\lhash.h" /Y',
			'copy "crypto\\rand\\rand.h" "inc32\\openssl\\rand.h" /Y',
			'copy "crypto\\err\\err.h" "inc32\\openssl\\err.h" /Y',
			'copy "crypto\\objects\\objects.h" "inc32\\openssl\\objects.h" /Y',
			'copy "crypto\\objects\\obj_mac.h" "inc32\\openssl\\obj_mac.h" /Y',
			'copy "crypto\\evp\\evp.h" "inc32\\openssl\\evp.h" /Y',
			'copy "crypto\\asn1\\asn1.h" "inc32\\openssl\\asn1.h" /Y',
			'copy "crypto\\asn1\\asn1_mac.h" "inc32\\openssl\\asn1_mac.h" /Y',
			'copy "crypto\\asn1\\asn1t.h" "inc32\\openssl\\asn1t.h" /Y',
			'copy "crypto\\pem\\pem.h" "inc32\\openssl\\pem.h" /Y',
			'copy "crypto\\pem\\pem2.h" "inc32\\openssl\\pem2.h" /Y',
			'copy "crypto\\x509\\x509.h" "inc32\\openssl\\x509.h" /Y',
			'copy "crypto\\x509\\x509_vfy.h" "inc32\\openssl\\x509_vfy.h" /Y',
			'copy "crypto\\x509v3\\x509v3.h" "inc32\\openssl\\x509v3.h" /Y',
			'copy "crypto\\cms\\cms.h" "inc32\\openssl\\cms.h" /Y',
			'copy "crypto\\conf\\conf.h" "inc32\\openssl\\conf.h" /Y',
			'copy "crypto\\conf\\conf_api.h" "inc32\\openssl\\conf_api.h" /Y',
			'copy "crypto\\txt_db\\txt_db.h" "inc32\\openssl\\txt_db.h" /Y',
			'copy "crypto\\pkcs7\\pkcs7.h" "inc32\\openssl\\pkcs7.h" /Y',
			'copy "crypto\\pkcs12\\pkcs12.h" "inc32\\openssl\\pkcs12.h" /Y',
			'copy "crypto\\comp\\comp.h" "inc32\\openssl\\comp.h" /Y',
			'copy "crypto\\engine\\engine.h" "inc32\\openssl\\engine.h" /Y',
			'copy "crypto\\ocsp\\ocsp.h" "inc32\\openssl\\ocsp.h" /Y',
			'copy "crypto\\ui\\ui.h" "inc32\\openssl\\ui.h" /Y',
			'copy "crypto\\ui\\ui_compat.h" "inc32\\openssl\\ui_compat.h" /Y',
			'copy "crypto\\krb5\\krb5_asn.h" "inc32\\openssl\\krb5_asn.h" /Y',
			'copy "crypto\\pqueue\\pqueue.h" "inc32\\openssl\\pqueue.h" /Y',
			'copy "crypto\\whrlpool\\whrlpool.h" "inc32\\openssl\\whrlpool.h" /Y',
			'copy "crypto\\ts\\ts.h" "inc32\\openssl\\ts.h" /Y',
			'copy "crypto\\srp\\srp.h" "inc32\\openssl\\srp.h" /Y',
			'copy "ssl\\ssl.h" "inc32\\openssl\\ssl.h" /Y',
			'copy "ssl\\ssl2.h" "inc32\\openssl\\ssl2.h" /Y',
			'copy "ssl\\ssl3.h" "inc32\\openssl\\ssl3.h" /Y',
			'copy "ssl\\ssl23.h" "inc32\\openssl\\ssl23.h" /Y',
			'copy "ssl\\tls1.h" "inc32\\openssl\\tls1.h" /Y',
			'copy "ssl\\dtls1.h" "inc32\\openssl\\dtls1.h" /Y',
			'copy "ssl\\kssl.h" "inc32\\openssl\\kssl.h" /Y',
			'copy "ssl\\srtp.h" "inc32\\openssl\\srtp.h"'
		}
		
		configuration 'x32'
			prebuildcommands {
				'copy "..\\CoherentThirdPartyFiles\\opensslconf_win32.h" "inc32\\openssl\\opensslconf.h" /Y',
			}
		configuration 'x64'
			prebuildcommands {
				'copy "..\\CoherentThirdPartyFiles\\opensslconf_win64.h" "inc32\\openssl\\opensslconf.h" /Y',
			}
		configuration '*'
		
		configuration 'not *Static'
			linkoptions { '/def:ms/LIBEAY32.def' }
		configuration '*'
	end
	